### ISSUE TITLE
Gridlines overwriting variants at certain zoom levels

### ISSUE THREAD

**Issue by colindaven** [elsiklab/multivariantviewer#16]
Hi,

I think I have found a bug or need some clarification. We have a very well known deletion present in the multisample VCF. It does not show up in the JBrowse plugin at certain zoom levels. 

The mutation is at coordinates close to a major coordinate position (117,199,645). I think the vertical major coordinate marker line in grey is overwriting the variant. Is there a way to guarantee writing the variants after the coordinate marker lines are drawn ?

Thanks and best wishes,
Colin

**Comment by cmdcolin** [comment]
There actually is a rendering optimization that was added that might have had the unintended side effects  of this happening. I'll double check and see

**Comment by cmdcolin** [comment]
I am not sure if the thing I was referring to is causing any problems, it was just a hypothesis.


I guess the way that  this plugin works is that it uses the default Box glyph from jbrowse, and the way that works is that if the feature is less than 1px wide, it makes it automatically 2px wide (` fRect.rect = { l: fRect.l, h: fRect.h, w: Math.max( fRect.w, 2 ), t: 0 };`)


Therefore it will always try to render a 2px wide thing but the major gridlines can hide it, especially because the color of the homozygous reference is a very similar grey to the gridlines


You could try modifying the colors a bit, e.g. make style->ref_color=brown and I believe it shows up better

![screenshot-localhost-2017-08-30-12-25-23](https://user-images.githubusercontent.com/6511937/29883451-5f2d466a-8d7e-11e7-8d8f-6845bfdc23bc.png)
![screenshot-localhost-2017-08-30-12-25-36](https://user-images.githubusercontent.com/6511937/29883452-5f30ec84-8d7e-11e7-9998-fbc324d9f4c8.png)


My choice of using grey was to match IGV but potentially the default could be changed

**Comment by colindaven** [comment]
Hi Colin, thanks for the detailed response. 

Looking into it further, it appears the one deletion in question isn't showing up at all for a different reason. This is a BBmap callvariants.sh deletion. As you can see the SNVs work well, but the deletion (which surely has genotypes as well) doesn't show up.

Looking at the docs more, I think I need "includeIndels": true, - and yes this works. Thanks for your help

![image](https://user-images.githubusercontent.com/6094884/29909797-d377d662-8e27-11e7-8722-05a9b8af0e85.png)

Thanks for the colour hints, I changed it to this for now. I'll see what feedback the users give.

         "style": {
             "ref_color"         : "yellow",
             "het_color"         : "orange",
             "hom_color"         : "red",
         },
