### ISSUE TITLE
Tooltips with html

### ISSUE THREAD

**Issue by mrouard** [elsiklab/multivariantviewer#6]
Hello @cmdcolin 

Is it possible to configure the conf file to make a tooltip appearing when clicking on the label and enrich the description with HTML links ?

Thanks

**Comment by cmdcolin** [comment]
There is currently code for a tooltip on mouseover/clicking and this can be customized with html links and such (and indeed, clicking the element that produces the tooltip helps when there are html links because it makes the tooltip stay open so that you can click on the links)

The showTooltips and showLabels option can be enabled, and an array of "sublabels" in the track config can specify the "description" which is shown in the tooltip that contains html stuff

I pushed an example to master here https://github.com/elsiklab/multivariantviewer/commit/9121ea71acc47f76ffad017c159b96ad47185ae1

**Comment by cmdcolin** [comment]
lemme know if that helps!

**Comment by mrouard** [comment]
Thank you. that's helpful.

How can I switch from mouseover to clicking?
The documentation only specifies 
showTooltips - Display mouseover tooltips with subtrack name and description (boolean)

**Comment by cmdcolin** [comment]
Hmm. There's not a basic flag for switching to mouse click instead of mouseover but I don't imagine it'd be too complicated to do that

**Comment by cmdcolin** [comment]
Went ahead and added a "clickTooltips" config option. Set that to true and combine that with showTooltips: true to get click tooltips :)

**Comment by cmdcolin** [comment]
Let me know if the clickTooltips option helps you out :) I guess close for now

**Comment by mrouard** [comment]
Many thanks for the new option. I have to update the system first and I will let you know.
